metrics:
    wordpress.installed:
        label: "Is WordPress installed?"
        matching_calls:
            php:
                - callee: "=WP::main"

    wordpress.get_option:
        label: "WordPress get_option"
        matching_calls:
            php:
                - callee:
                    selector: '=get_option'
                    argument:
                        1: '*'

    wordpress.get_option.raw:
        label: "WordPress get_option RAW (SQL query based)"
        matching_calls:
            php:
                - callee:
                      selector: '=wpdb::query'
                      argument:
                          1: '/.+ from wp_options/'
                  contrib: "count-only"

tests:
    "The homepage should be fast":
        path: "/"
        assertions:
            - "main.wall_time < 200ms"

# Read more about writing scenarios at https://blackfire.io/docs/builds-cookbooks/scenarios
scenarios: |
    #!blackfire-player

    scenario
        name 'The homepage should answer with a 200 status code'

        visit url('/')
            expect status_code() == 200
